name: C/C++ CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**/guessitTest.cpp'
jobs:
  guessit_job:
    runs-on: ubuntu-latest
    name: GuessIt Job
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: sudo apt-get update
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: make test
        run: make test
